package com.x7ff.steam.shared.util;

public enum CountryCode {
	US("US", "United States"),
	CA("CA", "Canada"),
	AF("AF", "Afghanistan"),
	AX("AX", "Aland Islands"),
	AL("AL", "Albania"),
	DZ("DZ", "Algeria"),
	AS("AS", "American Samoa"),
	AD("AD", "Andorra"),
	AO("AO", "Angola"),
	AI("AI", "Anguilla"),
	AQ("AQ", "Antarctica"),
	AG("AG", "Antigua &amp; Barbuda"),
	AR("AR", "Argentina"),
	AM("AM", "Armenia"),
	AW("AW", "Aruba"),
	AU("AU", "Australia"),
	AT("AT", "Austria"),
	AZ("AZ", "Azerbaijan"),
	BS("BS", "Bahamas"),
	BH("BH", "Bahrain"),
	BD("BD", "Bangladesh"),
	BB("BB", "Barbados"),
	BY("BY", "Belarus"),
	BE("BE", "Belgium"),
	BZ("BZ", "Belize"),
	BJ("BJ", "Benin"),
	BM("BM", "Bermuda"),
	BT("BT", "Bhutan"),
	BO("BO", "Bolivia"),
	BQ("BQ", "Bonaire, Sint Eustatius and Saba"),
	BA("BA", "Bosnia and Herzegovina"),
	BW("BW", "Botswana"),
	BV("BV", "Bouvet Island"),
	BR("BR", "Brazil"),
	IO("IO", "British Indian Ocean Territory"),
	VG("VG", "British Virgin Islands"),
	BN("BN", "Brunei Darussalam"),
	BG("BG", "Bulgaria"),
	BF("BF", "Burkina Faso"),
	BI("BI", "Burundi"),
	KH("KH", "Cambodia"),
	CM("CM", "Cameroon"),
	CV("CV", "Cape Verde"),
	KY("KY", "Cayman Islands"),
	CF("CF", "Central African Republic"),
	TD("TD", "Chad"),
	CL("CL", "Chile"),
	CN("CN", "China"),
	CX("CX", "Christmas Island"),
	CC("CC", "Cocos (Keeling) Islands"),
	CO("CO", "Colombia"),
	KM("KM", "Comoros"),
	CG("CG", "Congo"),
	CD("CD", "Congo, the Democratic Republic of the"),
	CK("CK", "Cook Iislands"),
	CR("CR", "Costa Rica"),
	CI("CI", "Cote D'ivoire (Ivory Coast)"),
	HR("HR", "Croatia"),
	CU("CU", "Cuba"),
	CW("CW", "Curacao"),
	CY("CY", "Cyprus"),
	CZ("CZ", "Czech Republic"),
	DK("DK", "Denmark"),
	DJ("DJ", "Djibouti"),
	DM("DM", "Dominica"),
	DO("DO", "Dominican Republic"),
	EC("EC", "Ecuador"),
	EG("EG", "Egypt"),
	SV("SV", "El Salvador"),
	GQ("GQ", "Equatorial Guinea"),
	ER("ER", "Eritrea"),
	EE("EE", "Estonia"),
	ET("ET", "Ethiopia"),
	FK("FK", "Falkland Islands (Malvinas)"),
	FO("FO", "Faroe Islands"),
	FJ("FJ", "Fiji"),
	FI("FI", "Finland"),
	FR("FR", "France"),
	GF("GF", "French Guiana"),
	PF("PF", "French Polynesia"),
	TF("TF", "French Southern Territories"),
	GA("GA", "Gabon"),
	GM("GM", "Gambia"),
	GE("GE", "Georgia"),
	DE("DE", "Germany"),
	GH("GH", "Ghana"),
	GI("GI", "Gibraltar"),
	GR("GR", "Greece"),
	GL("GL", "Greenland"),
	GD("GD", "Grenada"),
	GP("GP", "Guadeloupe"),
	GU("GU", "Guam"),
	GT("GT", "Guatemala"),
	GG("GG", "Guernsey"),
	GN("GN", "Guinea"),
	GW("GW", "Guinea-Bissau"),
	GY("GY", "Guyana"),
	HT("HT", "Haiti"),
	HM("HM", "Heard &amp; McDonald Islands"),
	HN("HN", "Honduras"),
	HK("HK", "Hong Kong"),
	HU("HU", "Hungary"),
	IS("IS", "Iceland"),
	IN("IN", "India"),
	ID("ID", "Indonesia"),
	IQ("IQ", "Iraq"),
	IE("IE", "Ireland"),
	IR("IR", "Islamic Republic of Iran"),
	IM("IM", "Isle of Man"),
	IL("IL", "Israel"),
	IT("IT", "Italy"),
	JM("JM", "Jamaica"),
	JP("JP", "Japan"),
	JE("JE", "Jersey"),
	JO("JO", "Jordan"),
	KZ("KZ", "Kazakhstan"),
	KE("KE", "Kenya"),
	KI("KI", "Kiribati"),
	KP("KP", "Korea, Democratic People's Republic of"),
	KR("KR", "Korea, Republic of"),
	KW("KW", "Kuwait"),
	KG("KG", "Kyrgyzstan"),
	LA("LA", "Laos"),
	LV("LV", "Latvia"),
	LB("LB", "Lebanon"),
	LS("LS", "Lesotho"),
	LR("LR", "Liberia"),
	LY("LY", "Libya"),
	LI("LI", "Liechtenstein"),
	LT("LT", "Lithuania"),
	LU("LU", "Luxembourg"),
	MO("MO", "Macau"),
	MK("MK", "Macedonia, The Former Yugoslav Republic of"),
	MG("MG", "Madagascar"),
	MW("MW", "Malawi"),
	MY("MY", "Malaysia"),
	MV("MV", "Maldives"),
	ML("ML", "Mali"),
	MT("MT", "Malta"),
	MH("MH", "Marshall Islands"),
	MQ("MQ", "Martinique"),
	MR("MR", "Mauritania"),
	MU("MU", "Mauritius"),
	YT("YT", "Mayotte"),
	MX("MX", "Mexico"),
	FM("FM", "Micronesia"),
	MD("MD", "Moldova, Republic of "),
	MC("MC", "Monaco"),
	MN("MN", "Mongolia"),
	MS("MS", "Monserrat"),
	ME("ME", "Montenegro"),
	MA("MA", "Morocco"),
	MZ("MZ", "Mozambique"),
	MM("MM", "Myanmar"),
	NA("NA", "Namibia"),
	NR("NR", "Nauru"),
	NP("NP", "Nepal"),
	NL("NL", "Netherlands"),
	NC("NC", "New Caledonia"),
	NZ("NZ", "New Zealand"),
	NI("NI", "Nicaragua"),
	NE("NE", "Niger"),
	NG("NG", "Nigeria"),
	NU("NU", "Niue"),
	NF("NF", "Norfolk Island"),
	MP("MP", "Northern Mariana Islands"),
	NO("NO", "Norway"),
	OM("OM", "Oman"),
	PK("PK", "Pakistan"),
	PW("PW", "Palau"),
	PS("PS", "Palestinian Territory, Occupied"),
	PA("PA", "Panama"),
	PG("PG", "Papua New Guinea"),
	PY("PY", "Paraguay"),
	PE("PE", "Peru"),
	PH("PH", "Philippines"),
	PN("PN", "Pitcairn"),
	PL("PL", "Poland"),
	PT("PT", "Portugal"),
	PR("PR", "Puerto Rico"),
	QA("QA", "Qatar"),
	RE("RE", "Reunion"),
	RO("RO", "Romania"),
	RU("RU", "Russian Federation"),
	RW("RW", "Rwanda"),
	BL("BL", "Saint Barthelemy"),
	LC("LC", "Saint Lucia"),
	MF("MF", "Saint Martin (French part)"),
	WS("WS", "Samoa"),
	SM("SM", "San Marino"),
	ST("ST", "Sao Tome &amp; Principe"),
	SA("SA", "Saudi Arabia"),
	SN("SN", "Senegal"),
	RS("RS", "Serbia"),
	SC("SC", "Seychelles"),
	SL("SL", "Sierra Leone"),
	SG("SG", "Singapore"),
	SX("SX", "Sint Maarten (Dutch part)"),
	SK("SK", "Slovakia"),
	SI("SI", "Slovenia"),
	SB("SB", "Solomon Islands"),
	SO("SO", "Somalia"),
	ZA("ZA", "South Africa"),
	GS("GS", "South Georgia and the South Sandwich Islands"),
	SS("SS", "South Sudan"),
	ES("ES", "Spain"),
	LK("LK", "Sri Lanka"),
	SH("SH", "St. Helena"),
	KN("KN", "St. Kitts and Nevis"),
	PM("PM", "St. Pierre &amp; Miquelon"),
	VC("VC", "St. Vincent &amp; the Grenadines"),
	SD("SD", "Sudan"),
	SR("SR", "Suriname"),
	SJ("SJ", "Svalbard &amp; Jan Mayen Islands"),
	SZ("SZ", "Swaziland"),
	SE("SE", "Sweden"),
	CH("CH", "Switzerland"),
	SY("SY", "Syrian Arab Republic"),
	TW("TW", "Taiwan"),
	TJ("TJ", "Tajikistan"),
	TZ("TZ", "Tanzania, United Republic of"),
	TH("TH", "Thailand"),
	TL("TL", "Timor-Leste"),
	TG("TG", "Togo"),
	TK("TK", "Tokelau"),
	TO("TO", "Tonga"),
	TT("TT", "Trinidad &amp; Tobago"),
	TN("TN", "Tunisia"),
	TR("TR", "Turkey"),
	TM("TM", "Turkmenistan"),
	TC("TC", "Turks &amp; Caicos Islands"),
	TV("TV", "Tuvalu"),
	UG("UG", "Uganda"),
	UA("UA", "Ukraine"),
	AE("AE", "United Arab Emirates"),
	GB("GB", "United Kingdom (Great Britain)"),
	UM("UM", "United States Minor Outlying"),
	VI("VI", "United States Virgin Islands"),
	UY("UY", "Uruguay"),
	UZ("UZ", "Uzbekistan"),
	VU("VU", "Vanuatu"),
	VA("VA", "Vatican City State (Holy See)"),
	VE("VE", "Venezuela"),
	VN("VN", "Viet Nam"),
	WF("WF", "Wallis &amp; Futuna Islands"),
	EH("EH", "Western Sahara"),
	YE("YE", "Yemen"),
	ZM("ZM", "Zambia"),
	ZW("ZW", "Zimbabwe");

	private final String code;
	private final String name;

	CountryCode(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public String getCountry() {
		return name;
	}

	public static CountryCode forName(String name) {
		for (CountryCode code : CountryCode.values()) {
			if (code.getCountry().equals(name)) {
				return code;
			}
		}
		return null;
	}

	public static String getCountry(String code) {
		for (CountryCode countryCode : CountryCode.values()) {
			if (countryCode.getCode().equals(code)) {
				return countryCode.getCountry();
			}
		}
		return null;
	}

}