--
-- Table for Game
--
CREATE TABLE game (
  app_id INTEGER NOT NULL,
  icon_url CHARACTER VARYING(255) NOT NULL,
  logo_url CHARACTER VARYING(255) NOT NULL,
  name CHARACTER VARYING(255) NOT NULL
);

ALTER TABLE ONLY game
ADD CONSTRAINT pk_game_id PRIMARY KEY (app_id);
