spring:
  main:
    banner-mode: 'OFF'
    web-environment: true
  profiles:
    active: development
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/steamtracker
    username: steamtracker
    password: steamtracker

server:
  port: 8888
  compression:
    enabled: true

security:
  enable-csrf: true

flyway:
  enabled: true
  locations:
    classpath:migrations